res might be null when node-fetch fails
For example:
```
TypeError: Request with GET/HEAD method cannot have body
```

is hidded because it prints:
```
TypeError: Cannot read property 'status' of undefined
```

Fixes #24